[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/.netlify/functions/route"
status = 200
force = true